# Generated by Django 2.2.5 on 2019-10-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('acc_type', models.CharField(max_length=50)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Branch')),
            ],
        ),
    ]
