# Generated by Django 2.2.5 on 2019-10-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_balance',
            field=models.BigIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
