# Generated by Django 2.2.5 on 2019-10-02 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bankuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='dob',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date of Birth'),
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('isDebit', models.BooleanField()),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Branch')),
            ],
        ),
    ]
