# Generated by Django 2.2.5 on 2019-10-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191002_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='acc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Account'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='acc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Account'),
        ),
    ]
