# Generated by Django 2.2.6 on 2019-10-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191002_1701'),
        ('myapp', '0005_atm'),
    ]

    operations = [
    ]
