# Generated by Django 2.2.6 on 2019-10-02 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20191002_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 17, 48, 36, 331809)),
        ),
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amt', models.IntegerField()),
                ('interest', models.FloatField()),
                ('installment', models.IntegerField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Loan')),
            ],
        ),
    ]
