# Generated by Django 2.2.6 on 2019-10-02 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191002_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emi',
            name='principal_amt',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 17, 53, 51, 273884)),
        ),
    ]
