# Generated by Django 2.2.6 on 2019-10-02 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20191002_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 18, 5, 25, 58726)),
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('interest', models.FloatField()),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Account')),
            ],
        ),
    ]
