# Generated by Django 2.2.6 on 2019-10-02 14:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20191002_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Loan', unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 20, 0, 40, 834168)),
        ),
    ]
