# Generated by Django 2.2.6 on 2019-10-03 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20191003_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit'), ('L', 'Loan')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 13, 30, 31, 145057)),
        ),
    ]
