# Generated by Django 2.2.6 on 2019-10-03 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20191003_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 13, 35, 57, 396966)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit'), ('L', 'Loan'), ('A', 'Account')], max_length=1),
        ),
    ]
