# Generated by Django 2.2.6 on 2019-10-03 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20191003_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 13, 42, 44, 10820)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Debit Card'), ('C', 'Credit Card'), ('L', 'Loan'), ('A', 'Account')], max_length=1),
        ),
    ]
