# Generated by Django 2.2.6 on 2019-10-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20191003_1512'),
        ('myapp', '0026_auto_20191003_1425'),
    ]

    operations = [
    ]
