# Generated by Django 2.2.6 on 2019-10-04 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_merge_20191003_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUser',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 6, 41, 31, 650820)),
        ),
    ]
